# Generated by Django 3.2 on 2024-10-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
